name: Continuous Deploy

on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - name: Checkout    
        uses: actions/checkout@v4

      - name: Setup modern yarn
        run: |
          corepack enable
          yarn set version stable
      
      - name: Install Dependencies Using yarn
        run: yarn install
      - name: Build
        run: yarn build
        
      - name: Push File to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:  
          username: ${{ secrets.USERNAME }}  #ssh user name
          server: ${{ secrets.HOST }}  #ssh server
          ssh_private_key: ${{ secrets.SSHKEY }}  #ssh private key
          local_path: './out/*' 
          remote_path: '/var/www/html'
